const markets=[
{group:'Equities · US',name:'S&P 500 proxy',symbol:'FOREXCOM:SPXUSD',note:'Cash CFD · index proxy',short:'S&P 500'},
{group:'Equities · US',name:'Nasdaq-100 proxy',symbol:'FOREXCOM:NSXUSD',note:'Cash CFD · Nasdaq-100 proxy',short:'Nasdaq-100'},
{group:'Equities · Europe',name:'FTSE 100 proxy',symbol:'FOREXCOM:UKXGBP',note:'Cash CFD · UK large-cap proxy',short:'FTSE 100'},
{group:'Equities · Europe',name:'Euro Stoxx 50',symbol:'INDEX:SX5E',note:'Euro-area blue-chip index · delay may apply',short:'Euro Stoxx 50'},
{group:'Equities · Asia',name:'Nikkei 225',symbol:'INDEX:NKY',note:'Japan equity index · delay may apply',short:'Nikkei 225'},
{group:'Equities · Asia',name:'Hang Seng Index',symbol:'INDEX:HSI',note:'Hong Kong equity index · end-of-day',short:'Hang Seng'},
{group:'Equities · Asia',name:'Shanghai Composite',symbol:'SSE:000001',note:'Mainland China equity index · delayed',short:'Shanghai'},
{group:'Equities · Asia',name:'BSE Sensex',symbol:'BSE:SENSEX',note:'India equity index · end-of-day',short:'Sensex'},
{group:'FX',name:'EUR / USD',symbol:'FX:EURUSD',note:'FX feed · real-time',short:'EUR / USD'},
{group:'FX',name:'GBP / USD',symbol:'FX:GBPUSD',note:'FX feed · real-time',short:'GBP / USD'},
{group:'FX',name:'USD / JPY',symbol:'FX:USDJPY',note:'FX feed · real-time',short:'USD / JPY'},
{group:'FX',name:'USD / offshore yuan',symbol:'FX:USDCNH',note:'Offshore yuan FX feed · real-time',short:'USD / CNH'},
{group:'Commodities',name:'Gold spot',symbol:'OANDA:XAUUSD',note:'Spot gold · USD per troy oz',short:'Gold'},
{group:'Commodities',name:'Brent oil proxy',symbol:'OANDA:BCOUSD',note:'Oil CFD · USD per barrel',short:'Brent oil'},
{group:'Bonds',name:'7–10Y Treasury ETF',symbol:'NASDAQ:IEF',note:'IEF · bond ETF price · delayed',short:'Treasuries · IEF'},
{group:'Bonds',name:'1–3Y Treasury ETF',symbol:'NASDAQ:SHY',note:'SHY · bond ETF price · delayed',short:'Short Treasuries'},
{group:'Crypto',name:'Bitcoin / USD',symbol:'COINBASE:BTCUSD',note:'Coinbase spot · real-time',short:'Bitcoin'},
{group:'Crypto',name:'Ethereum / USD',symbol:'COINBASE:ETHUSD',note:'Coinbase spot · real-time',short:'Ethereum'}];
const storage={get(k,f){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let theme=storage.get('market-room-theme','dark'), selected=markets[0],range='1M';
const timers=new Map();
function widget(id,type,config,label,link='https://www.tradingview.com/markets/'){
const host=document.getElementById(id);clearTimeout(timers.get(id));host.replaceChildren();
const wrap=document.createElement('div');wrap.className='tradingview-widget-container';
const content=document.createElement('div');content.className='tradingview-widget-container__widget';content.style.height='calc(100% - 26px)';
const credit=document.createElement('div');credit.className='tradingview-widget-copyright';const a=document.createElement('a');a.href=link;a.target='_blank';a.rel='noopener nofollow';a.textContent=label+' by TradingView';credit.append(a);wrap.append(content,credit);
const frame=document.createElement('iframe');frame.title=label+' TradingView widget';frame.style.cssText='width:100%;height:100%;border:0;display:block';frame.setAttribute('scrolling','no');frame.setAttribute('allowtransparency','true');
const cfg={...config,utm_source:location.hostname,utm_medium:'widget_new',utm_campaign:type,'page-uri':location.host+location.pathname};
frame.src='https://www.tradingview-widget.com/embed-widget/'+type+'/?locale=en#'+encodeURIComponent(JSON.stringify(cfg));
const loading=document.createElement('div');loading.className='feed-loading';loading.textContent='Connecting to market feed…';content.append(loading,frame);host.append(wrap);
frame.addEventListener('load',()=>{loading.remove();clearTimeout(timers.get(id))});
timers.set(id,setTimeout(()=>{if(loading.isConnected){loading.textContent='Chart not loading? ';const help=document.createElement('a');help.href=link;help.target='_blank';help.rel='noopener';help.textContent='Open source ↗';loading.append(help)}},15000));

}
function chart(){document.getElementById('chart-title').textContent=selected.name;document.getElementById('instrument-note').textContent=selected.note;document.getElementById('instrument').value=selected.symbol;document.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('active',b.dataset.range===range));widget('main-chart','advanced-chart',{autosize:true,symbol:selected.symbol,interval:range==='1D'?'5':range==='5D'?'30':'D',range,timezone:'Asia/Hong_Kong',theme,style:'3',locale:'en',allow_symbol_change:false,hide_top_toolbar:false,hide_side_toolbar:true,hide_volume:true,withdateranges:true,calendar:false,save_image:true,backgroundColor:theme==='dark'?'#181c25':'#ffffff',gridColor:theme==='dark'?'rgba(255,255,255,0.04)':'rgba(0,0,0,0.035)'},selected.name,'https://www.tradingview.com/chart/?symbol='+encodeURIComponent(selected.symbol));}
function render(){document.body.classList.toggle('dark',theme==='dark');document.getElementById('theme').textContent=theme==='dark'?'Light mode':'Dark mode';const snap=document.getElementById('snapshots');snap.replaceChildren();['FOREXCOM:SPXUSD','FX:EURUSD','OANDA:XAUUSD','NASDAQ:IEF','COINBASE:BTCUSD'].forEach(symbol=>{const m=markets.find(item=>item.symbol===symbol),i=markets.indexOf(m),card=document.createElement('article');card.className='snapshot';const top=document.createElement('div');top.className='snapshot-top';const b=document.createElement('button');b.textContent=m.group;b.setAttribute('aria-label','Explore '+m.name);b.onclick=()=>selectMarket(m.symbol);const type=document.createElement('span');type.className='snapshot-type';type.textContent=m.short;top.append(b,type);const h=document.createElement('div');h.id='mini-'+i;h.className='mini-host';const note=document.createElement('p');note.className='snapshot-note';note.textContent=m.note;card.append(top,h,note);snap.append(card);widget(h.id,'mini-symbol-overview',{symbol:m.symbol,width:'100%',height:'100%',locale:'en',dateRange:'1M',colorTheme:theme,isTransparent:false,autosize:true,largeChartUrl:'',chartOnly:false,noTimeScale:true},m.short,'https://www.tradingview.com/chart/?symbol='+encodeURIComponent(m.symbol));});chart();widget('market-watch','market-quotes',{width:'100%',height:'100%',colorTheme:theme,isTransparent:false,locale:'en',showSymbolLogo:false,symbolsGroups:[...new Set(markets.map(m=>m.group))].map(group=>({name:group,symbols:markets.filter(m=>m.group===group).map(m=>({name:m.symbol,displayName:m.name}))}))},'Market quotes');widget('news','timeline',{displayMode:'regular',feedMode:'all_symbols',colorTheme:theme,isTransparent:false,locale:'en',width:'100%',height:'100%'},'Market news','https://www.tradingview.com/news/');}
function selectMarket(symbol){const m=markets.find(m=>m.symbol===symbol);if(!m)throw new Error('Unsupported instrument');selected=m;chart();}
const select=document.getElementById('instrument');markets.forEach(m=>{const o=document.createElement('option');o.value=m.symbol;o.textContent=m.name;select.append(o)});select.onchange=()=>selectMarket(select.value);document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;chart()});document.getElementById('theme').onclick=()=>{theme=theme==='light'?'dark':'light';storage.set('market-room-theme',theme);render()};document.getElementById('reload').onclick=render;
function presentation(on){document.body.classList.toggle('present',on);document.getElementById('exit-present')?.remove();if(on){const b=document.createElement('button');b.id='exit-present';b.textContent='Exit presentation · Esc';b.onclick=()=>presentation(false);document.body.append(b)}}document.getElementById('present').onclick=()=>presentation(true);document.addEventListener('keydown',e=>{if(e.key==='Escape')presentation(false)});
function clock(){document.getElementById('clock').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Hong_Kong',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date())+' HKT'}clock();setInterval(clock,1000);
function renderBriefing(){const b=window.marketBriefing;if(!b)return;document.getElementById('briefing').innerHTML=`<div class="briefing-main"><div class="briefing-kicker"><p class="eyebrow">EXECUTIVE SUMMARY</p><span>Updated ${b.updatedAt}</span></div><h2>${b.headline}</h2><ul>${b.summary.map(x=>`<li>${x}</li>`).join('')}</ul></div><aside class="next-panel"><p class="eyebrow">WHAT TO WATCH NEXT</p>${b.calendar.map(e=>`<div class="calendar-row"><span>${e.day}</span><div><strong>${e.event}</strong><small>${e.impact}</small></div></div>`).join('')}</aside>`;document.getElementById('week-asof').textContent=b.asOf;document.getElementById('week-method').textContent=b.methodology;document.getElementById('week-grid').innerHTML=b.week.map(x=>`<article class="week-card ${x.tone}"><span>${x.label}</span><strong>${x.value}</strong></article>`).join('');document.getElementById('drivers-grid').innerHTML=b.drivers.map(x=>`<article class="panel driver-card"><div class="driver-top"><span>${x.asset}</span><strong>${x.move}</strong></div><div><p class="driver-label">WHY</p><p>${x.why}</p></div><div><p class="driver-label">WATCH NEXT</p><p>${x.watch}</p></div><a href="${x.url}" target="_blank" rel="noopener">${x.source} ↗</a></article>`).join('')}
document.getElementById('method-content').innerHTML='<p>Charts, quotes and live headlines are supplied by TradingView. Data streams automatically while the page is open. The written daily briefing is refreshed once each day from linked primary and reputable news sources. Refreshing the page does not remove an exchange delay.</p><h3>Read the instrument, not just the name</h3><ul><li>US index proxies use FOREX.com cash CFDs. They are not official exchange index prints.</li><li>Euro Stoxx 50, Nikkei 225 and Hang Seng use TradingView-supported index feeds. Hang Seng and BSE Sensex are end-of-day; other index feeds may also be delayed by their exchanges.</li><li>Gold uses OANDA spot pricing and Brent uses an OANDA CFD. These are provider quotes, not exchange futures settlement prices.</li><li>FX and Coinbase crypto use real-time feeds. Bond ETFs are delayed; other markets may be delayed or unavailable. Check the provider status and timestamp in the chart.</li><li>Bonds are represented by iShares Treasury ETFs: IEF holds 7–10 year Treasuries and SHY holds 1–3 year Treasuries. These are ETF prices, not Treasury yields. Price changes exclude distributions and are not total returns. Rising yields generally mean falling bond prices.</li></ul><h3>Written briefing</h3><p>Weekly figures compare the latest completed session with the prior weekly close unless otherwise noted. “Why” sections are sourced interpretations of market narratives, not proof of causation. Each card links to its supporting source.</p><h3>Time windows</h3><p>The top sparklines show one month. Explorer controls choose 1 day, 5 days, 1 month, 3 months or 1 year. Quote percentage changes follow the provider convention; they do not become period returns when the chart window changes.</p><h3>Morning Meeting</h3><p>Choose one asset class. State the movement and period, explain the leading drivers, then identify the next catalyst that could validate or reverse the move.</p><h3>AI process</h3><p>OpenAI Codex assisted with the dashboard design, implementation, briefing research and source documentation. TradingView supplies automatic market data and news. Independently verify figures before presenting.</p><p><a href="https://www.tradingview.com/widget-docs/faq/data/" target="_blank" rel="noopener">TradingView data policy ↗</a></p>';
const dialog=document.getElementById('method-dialog');document.getElementById('method-button').onclick=document.getElementById('feed-info').onclick=()=>dialog.showModal();document.getElementById('close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});renderBriefing();render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_market_view',description:'Select an instrument and chart window in Market Room.',inputSchema:{type:'object',properties:{symbol:{type:'string',enum:markets.map(m=>m.symbol)},period:{type:'string',enum:['1D','5D','1M','3M','12M']}},required:['symbol','period'],additionalProperties:false},execute(input){if(!markets.some(m=>m.symbol===input.symbol)||!['1D','5D','1M','3M','12M'].includes(input.period))throw new Error('Invalid market or period');range=input.period;selectMarket(input.symbol);return {symbol:selected.symbol,period:range,viewUpdated:true}},annotations:{readOnlyHint:false}})).catch(()=>{})}catch{}}
